### ISSUE TITLE
errors while building from source

### ISSUE THREAD

**Issue by muralikodali** [Usbac/nmly#2]
$ gcc -o nmly nmly.o 
giving following error

nmly.o: In function `getChanges':
nmly.c:(.text+0xe9): undefined reference to `strBefore'
nmly.c:(.text+0xfe): undefined reference to `strAfter'
nmly.c:(.text+0x11b): undefined reference to `strAfter'
nmly.c:(.text+0x1a8): undefined reference to `before'
nmly.c:(.text+0x1cf): undefined reference to `after'
nmly.c:(.text+0x1eb): undefined reference to `upper'
nmly.c:(.text+0x207): undefined reference to `lower'
nmly.c:(.text+0x234): undefined reference to `switchSides'
nmly.c:(.text+0x24d): undefined reference to `reverse'
nmly.c:(.text+0x279): undefined reference to `replace'
nmly.c:(.text+0x2a1): undefined reference to `replace'
collect2: error: ld returned 1 exit status

**Comment by Usbac** [comment]
The 'helper' file is the one that includes those functions. Nmly relies on that file so you must build it too. 

After that try `gcc -o nmly nmly.o helper.o`

Greetings!
