### ISSUE TITLE
Add file size based filter to utility.

### ISSUE THREAD

**Issue by Pratik32** [Usbac/nmly#4]
I wish to add a new filter to the utility. The file size based filter.
i.e the command will only run on the files which satisfy given file size constraints.
e.g
$ nmly reverse -d test/ -s -6G
This will only reverse files with size less than 6GB size.
$ nmly replace jpeg jpg -d ./ -s +15M
This will only work on files with size greater than equal to 15MB

**Comment by Usbac** [comment]
Done! Thank you so much for the new filter :)
